hotelProject/booking/urls.py
from django.urls import path
from django.http import HttpResponse, HttpRequest
from wkhtmltopdf.views import PDFTemplateView
from .views import MyPDF, customers
from . import printpdf
from . import views
from roomManager.views import GetRoom
# from django.conf.urls import url

from modernrpc.views import RPCEntryPoint

urlpatterns = [
    path('', printpdf.pdf_report_create, name='create-pdf'),
    path('pdf1', PDFTemplateView.as_view(template_name='pdfReport.html', filename='my_pdf.pdf'), name='pdf'),
    path('pdf2', MyPDF.as_view(template_name='pdfReport.html'), name='pdf'),
    path('pdf3', GetRoom.as_view(template_name='pdfRoom.html'), name='pdf'),

    path('rpc/', RPCEntryPoint.as_view()),
    path('customers/', views.customers),
    path('new/', views.newbooking, name="new_booking"),
    # path('searchforroom/', views.searchforroom,name="searchforroom"),
    path('search/<int:city>/<int:roomtype>/<str:checkin>/<str:checkout>', views.searchbooking, name='search_booking'),
]

hotelProject/hotelProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('booking/', include('booking.urls')),
    # path('roomManager/', include('roomManager.urls')),

    path('api/authentication/', include('apiauthentication.urls'), name='apiauthentication'),
    path('api/reviews/', include('apireviews.urls'), name='apireviews'),
    path('api/branches/', include('apibranches.urls'), name='apibranches'),
    path('api/services/', include('apiservices.urls'), name='apiservices'),
    path('reportBooking/', include('ReportBooking.urls'), name='reportBooking'),
    path('reportRoom/', include('ReportRoom.urls'), name='reportRoom'),
    path('booking/', include('booking.urls'), name='booking'),
    path('roomManager/', include('roomManager.urls'), name='roomManager'),
]

hotelProject/booking/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.core.validators import MinValueValidator, MaxValueValidator
from djmoney.models.fields import MoneyField
from django_countries.fields import CountryField
from roomManager.models import Room, RoomType, Service
from currencyapp.models import Currency
from django.contrib import admin


class Visitor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Identity_Card = (('Passport', 'Passport'), ('National ID', 'national identity'),)
    Identity_card_type = models.CharField(max_length=11, choices=Identity_Card, default='Passport')
    passport_picture = models.ImageField(null=True, upload_to='_img/')

    Identity_Card_number = models.CharField(max_length=20, null=True)
    birth_date = models.DateField(null=True, blank=True)
    nationality = CountryField(blank=True, default='Saudi Arabia')

    created_at = models.DateTimeField(default=datetime.datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now, blank=True)

    def __str__(self):
        return self.user.username


class Reservation(models.Model):
    BOOKING_type = (('B', 'Booking'),
                    ('R', 'Reception'),
                    ('T', 'Telephon'),
                    ('E', 'Email'))
    type = models.CharField(max_length=20, choices=BOOKING_type, default='B')
    BOOKING_STATUS = (('A', 'Available'),
                      ('B', 'Booked'),
                      ('C1', 'Cancelled by user'),
                      ('C2', 'Cancelled by Manager')
                      )
    booking_status = models.CharField(max_length=2, choices=BOOKING_STATUS, default='B')
    customer = models.ForeignKey(Visitor, on_delete=models.CASCADE)
    From_date = models.DateTimeField(verbose_name="From", blank=True, null=True)
    To_date = models.DateTimeField(verbose_name="To", null=True, blank=True)
    nb_days = models.PositiveIntegerField(verbose_name="nb_days", default=1)
    deadline_free_Cancelation = models.DateTimeField(blank=True, null=True)
    roomtype = models.ManyToManyField(RoomType, through='RoomBooked')
    _total_cost = models.DecimalField(max_digits=10, decimal_places=3)
    currency = models.ForeignKey(Currency,  on_delete=models.CASCADE)
    _discounted_price = models.DecimalField(max_digits=10, decimal_places=3)

    created_at = models.DateTimeField(default=datetime.datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now, blank=True)

    def __str__(self):
        return self.customer.user.username


class RoomBooked(models.Model):
    type = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    booking = models.ForeignKey(Reservation, on_delete=models.CASCADE)
    nb_Adults = models.PositiveIntegerField(verbose_name="Adults", default=1)  # nb od guests 1 or 2
    nb_Children = models.PositiveIntegerField(verbose_name="Children", default=0)  # nb od guests 1 or 2
    services = models.ManyToManyField(Service, related_name='services', through='ServiceBooked')
    visitor = models.ManyToManyField(Visitor, related_name='visitors', through='RoomVisitor')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, null=True)

    created_at = models.DateTimeField(default=datetime.datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now, blank=True)


class RoomBooked_Inline(admin.TabularInline):
    model = RoomBooked
    extra = 1


class RoomVisitor(models.Model):
    roombooked = models.ForeignKey(RoomBooked, on_delete=models.CASCADE)
    visitor = models.ForeignKey(Visitor, on_delete=models.CASCADE)

    created_at = models.DateTimeField(default=datetime.datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now, blank=True)


class RoomVisitor_Inline(admin.TabularInline):
    model = RoomVisitor
    extra = 1


class ServiceBooked(models.Model):
    room = models.ForeignKey(RoomBooked, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    qte = models.PositiveIntegerField()

    created_at = models.DateTimeField(default=datetime.datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now, blank=True)


class ServiceBooked_Inline(admin.TabularInline):
    model = ServiceBooked
    extra = 1


class ReservationAdmin(admin.ModelAdmin):
    list_display = ['booking_status', 'customer', 'From_date', 'To_date', 'nb_days',
                    'deadline_free_Cancelation', '_total_cost', '_discounted_price']
    fields = [('booking_status', 'customer'), ('From_date', 'To_date'),
              'nb_days', 'deadline_free_Cancelation', ('_total_cost', '_discounted_price')]
    inlines = (RoomBooked_Inline,)


class RoomBookedAdmin(admin.ModelAdmin):
    fields = ['room', ('nb_Adults', 'nb_Children')]
    inlines = (ServiceBooked_Inline,)


class CheckIn(models.Model):
    booking = models.ForeignKey(Reservation, on_delete=models.CASCADE, null=True)
    customer = models.ForeignKey(Visitor, related_name='customer', on_delete=models.CASCADE, null=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, null=False)
    check_in_date = models.DateTimeField(auto_now_add=True)
    check_out_date = models.DateTimeField(auto_now_add=True)
    nb_Adults = models.PositiveIntegerField(verbose_name="Adults", default=1)  # nb od guests 1 or 2
    nb_Children = models.PositiveIntegerField(verbose_name="Children", default=0)  # nb od guests 1 or 2
    visitor = models.ManyToManyField(Visitor, through='CheckInVisitor')

    created_at = models.DateTimeField(default=datetime.datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now, blank=True)

    def __str__(self):
        return self.room.title


class CheckInVisitor(models.Model):
    checkin = models.ForeignKey(CheckIn, on_delete=models.CASCADE)
    visitor = models.ForeignKey(Visitor, on_delete=models.CASCADE)

    created_at = models.DateTimeField(default=datetime.datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now, blank=True)


class CheckInVisitor_Inline(admin.TabularInline):
    model = CheckInVisitor
    extra = 1


class CheckInVisitorAdmin(admin.ModelAdmin):
    inlines = (CheckInVisitor_Inline,)


class Review(models.Model):
    usr = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    title = models.CharField(max_length=29, null=True)
    comment = models.TextField(max_length=250)  # models.IntegerField(default = 0)
    rate = models.PositiveIntegerField(default=3, validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(default=datetime.datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now, blank=True)

    def __str__(self):
        return self.comment

hotelProject/templates/new_booking.html
{%block title %} Create New Booking {%endblock%}
{% block breadcrumb %}
<li class=""><a href="{% url 'create-pdf' %}">Booking</a></li>

{%endblock%}

{% block content %}



{{type}}
<form method="POST">
    {% csrf_token %}
    <label>city</label><input type="text" name="city" id="id_city"><br/>
    <label>roomtype</label><input type="text" name="roomtype" id="id_roomtype"><br/>
    <label>checkin</label><input type="date" name="checkin" id="id_checkin"><br/>
    <label>checkout</label><input type="date" name="checkout" id="id_checkout"><br/>

    <input type="submit" value="book"/>
</form>


<div>

</div>
{%endblock%}

hotelProject/templates/pdfReport.html
<!doctype html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <style>
        .table,td
        {
            border:1px solid red;
        }
        td,th
        {
            text-align:center;
            padding-top:3px;
        }
        @font-face {
            font-family: "code2000";
            src: url("/fonts/CODE2000.TTF")
        }

        html {
                    font-family: code2000;
            }
    </style>
    <title>Show Info</title>
  </head>
  <body>
    <h1>Show Info From Das360</h1>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Id</th>
                        <th scope="col">booking_status</th>
                        <th scope="col">customer</th>
                        <th scope="col">booking_date</th>
                        <th scope="col">checking_date</th>
<!-- <img class="rounded-circle" src="{{userdata.avatar.url}}" alt="User Avatar" width="110">-->
                      </tr>
                    </thead>
                    <tbody>

                     {% for data in bookingdatatoshow %}

                        <tr>
                            <td >{{ data.id }}</td>

<!--                            {% with firstname="/static" %}-->
<!--                            <td class="m-2"> <img height="80px" width="50px" src="{{room.image.url}}" alt="User Avatar"/></td>-->
<!--                            <td class="m-2"> <img src="{{ firstname }}{{ room.image.url }}" style="height: 300px; width: 200px;"  class="card-img-top" alt="..."></td>-->
<!--                            {{ firstname }}{{ room.image.url }}-->

                            <td ><b>{{ data.customer }}</b></td>
                            <td>{{ data.booking_date }}</td>
                            <td style="color: blueviolet; margin: 5px;">{{ data.checking_date }}</td>
<!--                            <td>{{ room.is_published }}</td>-->
<!--                            <td>{{ room.created_at }}</td>-->

<!--<td><img src="{{hostname}}{{data.cover_image.url}}" alt="room image" ></td>-->
<!--                            <td><img class="rounded-circle" src="{{room.room_image.url}}" alt="room image" width="110"></td>-->
                        </tr>
<!--{% endwith %}-->
                      {% endfor %}

                    </tbody>
                  </table>

            </div>
        </div>
    </div>






    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </body>
</html>

hotelProject/templates/roomAvailabilityForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>room availability form</title>
</head>
<body style="text-align:center">
<h1>
    Room Availability Form <br><br>
</h1>
<form action="/reportBooking/roomAvailabilityForm/" method="GET">
    from date: <input type="date" name="from_date" id="idFromDate" required>
    to date: <input type="date" name="to_date" id="idToDate" required>
    <br>
    <br>
    Hotel id: <input type="number" name="Hotel_id" id="idHotelid" required>

<!--    select the room type:-->
<!--    <select id="roomtype" name="room_type" required>-->
<!--&lt;!&ndash;  <option value="volvo">Volvo</option>&ndash;&gt;-->
<!--&lt;!&ndash;  <option value="saab">Saab</option>&ndash;&gt;-->
<!--&lt;!&ndash;  <option value="fiat">Fiat</option>&ndash;&gt;-->
<!--&lt;!&ndash;  <option value="audi">Audi</option>&ndash;&gt;-->
<!--        <?php-->
<!--        $sql = mysqli_query($connection, "SELECT username FROM users");-->
<!--        while ($row = $sql->fetch_assoc()){-->
<!--        echo "<option value=\"owner1\">" . $row['username'] . "</option>";-->
<!--        }-->
<!--        ?>-->

<!--    </select>-->
    <input type="submit" name="FormRoomAvailability" value="Search"/>

</form>

</body>
</html>

hotelProject/templates/roomAvailabilityReport.html
<!doctype html>

<html lang="en">
    <head>
        <title> Room Availability Report </title>
    </head>

    <body style="text-align:center">

        <table border="5px solid black" align="center" style="width:80%" cellspacing="4px">
            <thead>
            <tr style="height:100px">

<!--                <th colspan="1" align= center> <img src="https://drive.google.com/uc?export=view&id=1A4oGJsCQz7FvS2rRjFGjV1kKbYgKgijm" alt="logo" width="50 px" height="50px"></th>-->
                <th colspan="3" align= center> <span style="color:YellowGreen;"> Hotel Room Availability Report,
                    from <span style="color:red;"> {{ fromDate }} </span>
                    to <span style="color:red;"> {{ toDate }} </span>
                </th>

            </tr>

            <tr align= center style="height:50px">
                <th style="color:darkblue;"> Room type </th>
                <th style="color:darkblue;"> Reserved </th>
                <th style="color:darkblue;"> Available </th>
            </tr>
            </thead>
            <tbody>

            {% for x in rtypeList %}
            <tr align= center>
                <td> <span style="color:red;">  -Type: </span> {{ x.roomTname }}
                     <span style="color:red;"> |-Bed type: </span>{{ x.bedType }}
                     <span style="color:red;"> |-Area: </span>{{ x.roomTarea }}
                     <span style="color:red;"> |-Capacity: </span>{{ x.capacity }}
                     <span style="color:red;"> |-Price per day: </span>{{ x.roomTprice }}
                </td>
                <td> {{ x.countReserved }} </td>
                <td> {{ x.countAvailable }} </td>
            </tr>
            {% endfor %}


            <tr align= center style="height:30px">
                <td style="color:darkblue;"> <b> Total </b> </td>
                <td> {{ totalReserved }} </td>
                <td> {{ totalAvailable }} </td>

            </tr>
            </tbody>
        </table>
        <h4 style=" color: grey">press "Ctrl + P"  to make PDF </h4>
    </body>
</html>